version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily" 
    target-branch: "main"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily" 
    target-branch: "builder"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "builder"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily" 
    target-branch: "edge-builder"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "edge-builder"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily" 
    target-branch: "v3.22"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "v3.22"  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily" 
    target-branch: "beta"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "beta"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily" 
    target-branch: "v3.21"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "v3.21"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily" 
    target-branch: "v3.20"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "v3.20"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily" 
    target-branch: "v3.19"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "v3.19"  
